# This config file is useful in the upgrade tests, where we upgrade from
# either the latest stable chart or the latest dev release of the chart. This
# config is only applied to the chart we upgrade to. It helps us handle
# situations when we add new configuration options that would fail with a schema
# validation error in the previous chart versions.
#
# Note that one could think that it would be possible to have dev-config.yaml
# include this config and then pass --set hub.some-option=null to null it out
# when it must not be passed, but that still triggers schema validation errors.
#
hub:
  # FIXME: move loadRoles to dev-config.yaml after 2.0.0 is released.
  loadRoles:
    test-scoped-access:
      description: Used to JupyterHub 2.0.0+ RBAC scoped access, currently to the /hub/api/info endpoint via read:hub.
      scopes: [read:hub]
      services: [test-with-scoped-access]
    test-role-with-explicit-name:
      name: test-role-2
      description: Access to users' information and group membership
      scopes: [users, groups]
      users: [cyclops, gandalf]
      services: [test]
      groups: []

singleuser:
  # FIXME: move resources to dev-config.yaml after 2.0.0 is released.
  networkPolicy:
    egressAllowRules:
      nonPrivateIPs: false
  networkTools:
    # FIXME: move resources to dev-config.yaml after 2.0.0 is released.
    resources:
      requests:
        memory: 0
        cpu: 0
